### PR TITLE
Match version of bitcore provided by storj-lib

### PR DESCRIPTION
**Pull request by retrohacker**
Solves #43

### CODE REVIEW

**Review by dylanlott — APPROVED** [review]
LGTM

**Comment by nginnever** [comment]
I am still getting the error reported in #43 

Can you explain further how setting the module versions equal to eachother would prevent this check from failing. 

From what I have seen this check looks at global to see if bitcore-lib has been defined on it and throws an err if it has. The function is called versionGuard but it seems to really be an instance guard that will error out regardless if this versions match if i'm not mistaken.

In our case storj.js first requires core which in turn requires bitcore-lib and gets defined on global. Then storj.js tries to require bitcore-lib but one of its submodules has already defined it on global so the check fails.

**Comment by retrohacker** [comment]
@nginnever 

https://github.com/bitpay/bitcore-lib/blob/ed026854b27b4554ac52a44743972a7b82d97f5d/index.js#L15-L16

Those lines only get executed once assuming the `require('bitcore-lib')` is pulling the same path on the fs. The second time you require a module, instead of loading and executing it, it returns a cached module off of `require.cache`.

To test out this behaviour, create this file:

`index.js`

```javascript
module.exports = function() { console.log('calling function') }
console.log('cache miss')
```

Then run:

```text
$ node
> require('./index.js')()
cache miss
calling function
undefined
> require('./index.js')()
calling function
undefined
```

The second invocation didn't execute the top level `console.log`

**Comment by retrohacker** [comment]
If you have two separate versions of `bitcore-lib` in your `node_modules` directory, they will both initialize their own separate `require.cache`, the second one will then pick up on the `global` value being set and be sad.

**Comment by nginnever** [comment]
Yeah false alarm, I was doing my own linkage while testing crypto upgrades to core so I ended up tricking it into requiring twice. 

Remove the link fixed this for me. Thanks

**Pull request merged**
