### PR TITLE
Updates 

### PR DESCRIPTION
**Pull request by nginnever**

### CODE REVIEW

**Comment by retrohacker** [comment]
Weird failure, env var wasn't injected into the travis build. Re-running test.

**Comment by retrohacker** [comment]
🤔

**Comment by nginnever** [comment]
Not sure what's up with travis. I'm going to push a few more commits into this PR anyway.

**Comment by retrohacker** [comment]
Could you break these out into separate PRs? They are unrelated changes.

**Comment by retrohacker** [comment]
Fighting with stack traces ATM, will figure out travis when I'm done with that :-)

**Comment by nginnever** [comment]
There are only 3 lines changed in this. I would need to create a separate branch just to update a version number. I'll just leave that off until we figure out why travis is failing and leave this as just fixing uploads.

**Comment by retrohacker** [comment]
@nginnever solved in #48, will merge into a branch and do the test from there. Can't run Travis tests off of a fork.

**Comment by retrohacker** [comment]
@nginnever LMK when this is ready to merge (still has WIP in the title) and I'll go ahead and pull it into a branch from the repo to run the tests.

**Comment by nginnever** [comment]
Thanks @retrohacker good to know about travis.

These changes are minimal so feel free to merge to branch

**Pull request merged**
