### PR TITLE
`generateMnemonic` -> `generateEncryptionKey`

### PR DESCRIPTION
**Pull request by retrohacker**

### CODE REVIEW

**Comment by retrohacker** [comment]
closes #38

**Review by dylanlott — APPROVED** [review]
LGTM

**Comment by nginnever** [comment]
Mnemonic is still blocking storj.js in the browser for me. see #43

**Comment by retrohacker** [comment]
Separate issue from this PR, related to semver ranges.

Will merge and track in https://github.com/Storj/storj.js/issues/43

**Pull request merged**
